AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nimo-exercise
Transform:
- AWS::Serverless-2016-10-31

Resources:
  getCoinCurrentPrice:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/get-coin-current-price.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get current price of a specific cryptocurrency that indicate on path parameter and receive an email about the result
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref SearchHistoryTable
      - SESCrudPolicy:
          IdentityName: !Ref SESEmailIdentity
      - Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'ses:SendEmail'
              - 'ses:SendRawEmail'
            Resource: '*'

      Environment:
        Variables:
          SEARCH_HISTORY_TABLE: !Ref SearchHistoryTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /coin/{id}/current
            Method: GET

  getSearchHistory:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/get-search-history.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get cryptocurrency search history
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref SearchHistoryTable
      Environment:
        Variables:
          SEARCH_HISTORY_TABLE: !Ref SearchHistoryTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /history
            Method: GET

  SearchHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk # TODO: change to userId
          AttributeType: S
        - AttributeName: sk # TODO: change to coinId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S

      KeySchema:
        - AttributeName: pk # TODO: change to userId
          KeyType: HASH
        - AttributeName: sk # TODO: change to coinId
          KeyType: RANGE

      LocalSecondaryIndexes:
        - IndexName: userId-timestamp-index
          KeySchema:
            - AttributeName: pk # TODO: change to userId
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - sk # TODO: change to coinId


      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true

  SESEmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: "thanchanok.lks@gmail.com"

  SESEmailIdentity2:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: "thanchanok.likitsinsopon@gmail.com"

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
